language: c
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get -qq update
script: ./bootstrap                                 \
     && ./configure                                 \
     && make                                        \
     && make check || (cat test-suite.log && false)
