dist: bionic
language: c
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install doxygen graphviz
script:
  - ./bootstrap
  - ./configure
  - make all
  - export LD_LIBRARY_PATH=$(if [[ "$CC" == "clang" ]]; then echo -n '/usr/local/clang/lib'; fi)
  - make check VERBOSE=1
  - make html
